/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.2.115 */
/* Module Version: 4.9 */
/* Sat Dec 15 23:31:29 2018 */

/* parameterized module instance */
Multiplier __ (.Clock( ), .ClkEn( ), .Aclr( ), .DataA( ), .DataB( ), 
    .Result( ));
