/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.2.115 */
/* Module Version: 5.7 */
/* Wed Dec 05 20:22:47 2018 */

/* parameterized module instance */
PLL __ (.CLKI( ), .CLKOP( ));
