/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.3.144 */
/* Module Version: 5.7 */
/* Mon Jun 03 21:31:44 2019 */

/* parameterized module instance */
PLL __ (.CLKI( ), .CLKOP( ));
