/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.10.2.115 */
/* Module Version: 1.6 */
/* C:\lscc\diamond\3.10_x64\ispfpga\bin\nt64\scuba.exe -w -n SinCos -lang verilog -synth lse -bus_exp 7 -bb -arch xo2c00 -type cosine -addr_width 8 -width 8 -pfu -mode 2 -output_reg  */
/* Wed Dec 05 22:13:12 2018 */


`timescale 1 ns / 1 ps
module SinCos (Clock, ClkEn, Reset, Theta, Sine, Cosine)/* synthesis NGD_DRC_MASK=1 */;
    input wire Clock;
    input wire ClkEn;
    input wire Reset;
    input wire [7:0] Theta;
    output wire [7:0] Sine;
    output wire [7:0] Cosine;

    wire Sine_7_ffin;
    wire Sine_6_ffin;
    wire Sine_5_ffin;
    wire Sine_4_ffin;
    wire Sine_3_ffin;
    wire Sine_2_ffin;
    wire Sine_1_ffin;
    wire Sine_0_ffin;
    wire Cosine_7_ffin;
    wire Cosine_6_ffin;
    wire Cosine_5_ffin;
    wire Cosine_4_ffin;
    wire Cosine_3_ffin;
    wire Cosine_2_ffin;
    wire Cosine_1_ffin;
    wire Cosine_0_ffin;

    FD1P3DX FF_15 (.D(Sine_7_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[7]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_14 (.D(Sine_6_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[6]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_13 (.D(Sine_5_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[5]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_12 (.D(Sine_4_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[4]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_11 (.D(Sine_3_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[3]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_10 (.D(Sine_2_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[2]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_9 (.D(Sine_1_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(Sine[1]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_8 (.D(Sine_0_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(Sine[0]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_7 (.D(Cosine_7_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Cosine[7]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_6 (.D(Cosine_6_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Cosine[6]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_5 (.D(Cosine_5_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Cosine[5]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_4 (.D(Cosine_4_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Cosine[4]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_3 (.D(Cosine_3_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Cosine[3]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_2 (.D(Cosine_2_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Cosine[2]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_1 (.D(Cosine_1_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Cosine[1]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_0 (.D(Cosine_0_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Cosine[0]))
             /* synthesis GSR="ENABLED" */;

    defparam triglut_1_0_15.initval = 256'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE00000000000000000000000000000000 ;
    ROM256X1A triglut_1_0_15 (.AD7(Theta[7]), .AD6(Theta[6]), .AD5(Theta[5]), 
        .AD4(Theta[4]), .AD3(Theta[3]), .AD2(Theta[2]), .AD1(Theta[1]), 
        .AD0(Theta[0]), .DO0(Sine_7_ffin));

    defparam triglut_1_0_14.initval = 256'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE000000000000003FF800000000000000 ;
    ROM256X1A triglut_1_0_14 (.AD7(Theta[7]), .AD6(Theta[6]), .AD5(Theta[5]), 
        .AD4(Theta[4]), .AD3(Theta[3]), .AD2(Theta[2]), .AD1(Theta[1]), 
        .AD0(Theta[0]), .DO0(Sine_6_ffin));

    defparam triglut_1_0_13.initval = 256'hFFFFF8000000000000000000003FFFFE00000FFFFFFFFFC007FFFFFFFFE00000 ;
    ROM256X1A triglut_1_0_13 (.AD7(Theta[7]), .AD6(Theta[6]), .AD5(Theta[5]), 
        .AD4(Theta[4]), .AD3(Theta[3]), .AD2(Theta[2]), .AD1(Theta[1]), 
        .AD0(Theta[0]), .DO0(Sine_5_ffin));

    defparam triglut_1_0_12.initval = 256'hFFC007FFE00000000000000FFFC007FE007FF0003FFFFFC007FFFFF8001FFC00 ;
    ROM256X1A triglut_1_0_12 (.AD7(Theta[7]), .AD6(Theta[6]), .AD5(Theta[5]), 
        .AD4(Theta[4]), .AD3(Theta[3]), .AD2(Theta[2]), .AD1(Theta[1]), 
        .AD0(Theta[0]), .DO0(Sine_4_ffin));

    defparam triglut_1_0_11.initval = 256'hF83F07E01FF0000000001FF00FC1F83E0F81F01FC03FFFC007FFF807F01F03E0 ;
    ROM256X1A triglut_1_0_11 (.AD7(Theta[7]), .AD6(Theta[6]), .AD5(Theta[5]), 
        .AD4(Theta[4]), .AD3(Theta[3]), .AD2(Theta[2]), .AD1(Theta[1]), 
        .AD0(Theta[0]), .DO0(Sine_3_ffin));

    defparam triglut_1_0_10.initval = 256'hC738C71E1E0FC0000007E0F0F1C639C6318E31E3C3C0FFC007FE07878F18E318 ;
    ROM256X1A triglut_1_0_10 (.AD7(Theta[7]), .AD6(Theta[6]), .AD5(Theta[5]), 
        .AD4(Theta[4]), .AD3(Theta[3]), .AD2(Theta[2]), .AD1(Theta[1]), 
        .AD0(Theta[0]), .DO0(Sine_2_ffin));

    defparam triglut_1_0_9.initval = 256'hB4A4B6D9998C3E0000F8633336DA4A5AD296D26CCCC70FC007E1C6666C96D296 ;
    ROM256X1A triglut_1_0_9 (.AD7(Theta[7]), .AD6(Theta[6]), .AD5(Theta[5]), 
        .AD4(Theta[4]), .AD3(Theta[3]), .AD2(Theta[2]), .AD1(Theta[1]), 
        .AD0(Theta[0]), .DO0(Sine_1_ffin));

    defparam triglut_1_0_8.initval = 256'h663264B5554B31C00719A5555A4C98CC663264B5554B31C00719A5555A4C98CC ;
    ROM256X1A triglut_1_0_8 (.AD7(Theta[7]), .AD6(Theta[6]), .AD5(Theta[5]), 
        .AD4(Theta[4]), .AD3(Theta[3]), .AD2(Theta[2]), .AD1(Theta[1]), 
        .AD0(Theta[0]), .DO0(Sine_0_ffin));

    defparam triglut_1_0_7.initval = 256'h0000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE0000000000000000 ;
    ROM256X1A triglut_1_0_7 (.AD7(Theta[7]), .AD6(Theta[6]), .AD5(Theta[5]), 
        .AD4(Theta[4]), .AD3(Theta[3]), .AD2(Theta[2]), .AD1(Theta[1]), 
        .AD0(Theta[0]), .DO0(Cosine_7_ffin));

    defparam triglut_1_0_6.initval = 256'hF800000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE000000000000003F ;
    ROM256X1A triglut_1_0_6 (.AD7(Theta[7]), .AD6(Theta[6]), .AD5(Theta[5]), 
        .AD4(Theta[4]), .AD3(Theta[3]), .AD2(Theta[2]), .AD1(Theta[1]), 
        .AD0(Theta[0]), .DO0(Cosine_6_ffin));

    defparam triglut_1_0_5.initval = 256'h07FFFFFFFFE00000FFFFF8000000000000000000003FFFFE00000FFFFFFFFFC0 ;
    ROM256X1A triglut_1_0_5 (.AD7(Theta[7]), .AD6(Theta[6]), .AD5(Theta[5]), 
        .AD4(Theta[4]), .AD3(Theta[3]), .AD2(Theta[2]), .AD1(Theta[1]), 
        .AD0(Theta[0]), .DO0(Cosine_5_ffin));

    defparam triglut_1_0_4.initval = 256'h07FFFFF8001FFC00FFC007FFE00000000000000FFFC007FE007FF0003FFFFFC0 ;
    ROM256X1A triglut_1_0_4 (.AD7(Theta[7]), .AD6(Theta[6]), .AD5(Theta[5]), 
        .AD4(Theta[4]), .AD3(Theta[3]), .AD2(Theta[2]), .AD1(Theta[1]), 
        .AD0(Theta[0]), .DO0(Cosine_4_ffin));

    defparam triglut_1_0_3.initval = 256'h07FFF807F01F03E0F83F07E01FF0000000001FF00FC1F83E0F81F01FC03FFFC0 ;
    ROM256X1A triglut_1_0_3 (.AD7(Theta[7]), .AD6(Theta[6]), .AD5(Theta[5]), 
        .AD4(Theta[4]), .AD3(Theta[3]), .AD2(Theta[2]), .AD1(Theta[1]), 
        .AD0(Theta[0]), .DO0(Cosine_3_ffin));

    defparam triglut_1_0_2.initval = 256'h07FE07878F18E318C738C71E1E0FC0000007E0F0F1C639C6318E31E3C3C0FFC0 ;
    ROM256X1A triglut_1_0_2 (.AD7(Theta[7]), .AD6(Theta[6]), .AD5(Theta[5]), 
        .AD4(Theta[4]), .AD3(Theta[3]), .AD2(Theta[2]), .AD1(Theta[1]), 
        .AD0(Theta[0]), .DO0(Cosine_2_ffin));

    defparam triglut_1_0_1.initval = 256'h07E1C6666C96D296B4A4B6D9998C3E0000F8633336DA4A5AD296D26CCCC70FC0 ;
    ROM256X1A triglut_1_0_1 (.AD7(Theta[7]), .AD6(Theta[6]), .AD5(Theta[5]), 
        .AD4(Theta[4]), .AD3(Theta[3]), .AD2(Theta[2]), .AD1(Theta[1]), 
        .AD0(Theta[0]), .DO0(Cosine_1_ffin));

    defparam triglut_1_0_0.initval = 256'h0719A5555A4C98CC663264B5554B31C00719A5555A4C98CC663264B5554B31C0 ;
    ROM256X1A triglut_1_0_0 (.AD7(Theta[7]), .AD6(Theta[6]), .AD5(Theta[5]), 
        .AD4(Theta[4]), .AD3(Theta[3]), .AD2(Theta[2]), .AD1(Theta[1]), 
        .AD0(Theta[0]), .DO0(Cosine_0_ffin));



    // exemplar begin
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
